#include <sega_xpt.h>

//background tiles
#include "graphic/roarbg.c"
#include "graphic/roarframes.c"
#include "graphic/girl1.c"
#include "graphic/girl2.c"
#include "graphic/girl3.c"
#include "graphic/girl4.c"
#include "graphic/girl5.c"
#include "graphic/stars.c"
#include "graphic/title.c"
#include "graphic/metalorange.c"
#include "graphic/cyberblock.c"
#include "graphic/chipframes.c"
#include "graphic/menufont.c"
#include "graphic/game_tiles.c"
#include "graphic/chipgame.c"
#include "graphic/gamestar.c"
#include "graphic/soon.c"
#include "graphic/tomo.c"
#include "graphic/cutscfont.c"
#include "graphic/gameover.c"
#include "graphic/chipover.c"
#include "graphic/noticefont.c"

//maps
#include "graphic/starnear.c"
#include "graphic/starmid.c"
#include "graphic/starfar.c"
#include "graphic/game.c"
#include "graphic/gamenear.c"
#include "graphic/gamemid.c"
#include "graphic/gamefar.c"

//sprites
#include "graphic/ball.c"
#include "graphic/font.c"
#include "graphic/starspr.c"
#include "graphic/ship.c"
#include "graphic/explosion.c"
#include "graphic/beffect.c"
#include "graphic/blocks1.c"
#include "graphic/blocks2.c"
#include "graphic/blockcrack.c"
#include "graphic/capsule.c"
#include "graphic/bit.c"
#include "graphic/laser.c"
#include "graphic/barrier.c"
#include "graphic/introfont.c"
#include "graphic/circle.c"
